### ISSUE TITLE
感谢提供

### ISSUE THREAD

**Issue by banduoba** [ufan0/kill-douyin-watermark#1]
正好有需要,感谢!加油楼主,我是昌北读的

**Comment by banduoba** [comment]
点击还原之后 点击下载视频跳转后提示视频不见啦 这个是什么情况呢

**Comment by AllinProgram** [comment]
抱歉，现在才看见，未看见Github邮件提醒。

你说的情况应该是这样的：

抖音分享出来的链接是具有时效性的，有效期具体多久我没有测试。

过期会导致你所指出来的情况。

**Comment by banduoba** [comment]
@ufan0 不过我是立即分享后获取的链接 不是过期了好久

**Comment by AllinProgram** [comment]
> @ ufan0不过我是立即分享后获取的链接不是过期了好久

这个我没遇见过，应该是小概率事件，目前无法解决，抱歉了。

**Comment by ufan0** [comment]
> 正好有需要,感谢!加油楼主,我是昌北读的

看了您的repo，对您的技术栈很感兴趣，不知能否加个联系方式，身边实在是缺同道人！

没有找到您的邮箱，我的邮箱ufan0@foxmail.com。
